### ISSUE TITLE
runserver work but import does not

### ISSUE THREAD

**Issue by mathieu660** [chrisspen/django-sec#5]
Hello, 

I can run the server and see the webpage, but I can not use the sec_import_index. 

Here is the error I get : 
`C:\Users\Math\math_sec>python manage.py sec_import_index --start-year=2015 --end-year=2016
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 208, in fetch_command
    klass = load_command_class(app_name, subcommand)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 40, in load_command_class
    module = import_module('%s.management.commands.%s' % (app_name, name))
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Python27\lib\site-packages\django_sec\management\commands\sec_import_index.py", line 12, in <module>
    from django.core.management.base import NoArgsCommand
ImportError: cannot import name NoArgsCommand`

Any way to fix this

**Comment by robomotic** [comment]
It seems just a missing package isn't it ?

**Comment by mathieu660** [comment]
Could you please elaborate. I do get this when i call manage,py 


Available subcommands:

[auth]
    changepassword
    createsuperuser

[django]
    check
    compilemessages
    createcachetable
    dbshell
    diffsettings
    dumpdata
    flush
    inspectdb
    loaddata
    makemessages
    makemigrations
    migrate
    sendtestemail
    shell
    showmigrations
    sqlflush
    sqlmigrate
    sqlsequencereset
    squashmigrations
    startapp
    startproject
    test
    testserver

[django_sec]
    sec_import_attrs
    sec_import_index
    sec_mark_units
    sec_xbrl_to_csv

[sessions]
    clearsessions

[staticfiles]
    collectstatic
    findstatic
    runserver

I am not a developer and I am trying to get a grip of this ...

**Comment by chrisspen** [comment]
This was caused by the code not supporting Django 1.10. This should now be fixed.

**Comment by mathieu660** [comment]
Thank you !
