### ISSUE TITLE
sec_import_index issue #2

### ISSUE THREAD

**Issue by mathieu660** [chrisspen/django-sec#8]
I noticed that sec_import_index hang when downloading years 2016,2015,2014,2013 qtr2 etc. Strange thing is it will work for qrt 1 of 2013...

`C:\Users\Math\math_sec>python manage.py sec_import_index --start-year=2013 --end-year=2016
Opening index file /tmp/django_sec\company_2013_1.zip.
Found 475 prior ciks.
Processing record 303583 of 303583 (100.00%).

73537 new companies found.
301393 new indexes found.
Downloading ftp://ftp.sec.gov/edgar/full-index/2013/QTR2/company.zip.
Opening index file /tmp/django_sec\company_2013_2.zip.
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "C:\Python27\lib\site-packages\django\core\management\__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "C:\Python27\lib\site-packages\django_sec\management\commands\sec_import_index.py", line 111, in handle
    max_lines=max_lines)
  File "C:\Python27\lib\site-packages\django_sec\management\commands\sec_import_index.py", line 163, in get_filing_list
    zipf = ZipFile(fn)
  File "C:\Python27\lib\zipfile.py", line 770, in __init__
    self._RealGetContents()
  File "C:\Python27\lib\zipfile.py", line 811, in _RealGetContents
    raise BadZipfile, "File is not a zip file"
zipfile.BadZipfile: File is not a zip file`

**Comment by chrisspen** [comment]
I encountered that a few times myself. It looks like the file may be corrupted. Try deleting it from /tmp and re-running the download.
