### ISSUE TITLE
Script slowness and excel export does not work

### ISSUE THREAD

**Issue by mathieu660** [chrisspen/django-sec#9]
1.	Parsing all the data for a specific year seems to take forever (more than a week). Is this normal ? Is there any way the script could run faster by downloading all the files at the beginning and parse the data in several files at the same time ? 
2.	Exporting the data to excel seem broken.

**Comment by clapas** [comment]
I am also experiencing problems with the `sec_xbrl_to_csv` subcommand:

```
Traceback (most recent call last):
  File "/usr/local/bin/django-admin", line 11, in <module>
    sys.exit(execute_from_command_line())
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 363, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/__init__.py", line 355, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python2.7/dist-packages/django/core/management/base.py", line 332, in execute
    output = self.handle(*args, **options)
TypeError: handle() takes exactly 2 arguments (1 given)
```
